---
title: "05_reliability_scales"
output: html_document
date: "2026-03-20"
---

# Carregamento de pacotes
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(expss)
library(igraph)
library(lme4)
library(lmerTest)
library(mlmRev)
library(psych)
library(qgraph)
library(ggplot2)
```

# Análise Fatorial Metas de realização

```{r}
# names(df_geral) # Itens do 58:74
```

```{r}
df_geral %>% select(58:74) %>% KMO()
df_geral %>% select(58:74) %>% bartlett.test()
```

```{r}
poly_meta <- df_geral %>% select(58:74) %>% polychoric(.)   # matriz de correlações policóricas para análise paralela.
rho_meta <- poly_meta$rho # guardando apenas o Rho de Spearman da matriz de correlações policóricas
scree_meta <-scree(rho_meta)

pa_meta <- fa.parallel(rho_meta, n.obs=209, fa="fa") # análise paralela sobre a matriz de correlações policóricas
pa_meta$fa.values #mostra os eigenvalues com os dados experimentais
pa_meta$fa.sim #mostra os eigenvalues com os dados simulados
```

```{r}
# Fatores

meta_efa <- df_geral %>% select(58:74) %>% fa(nfactors = '3', cor='poly', 
            fm='wls', rotate = 'geominQ')

meta_efa$e.values
meta_efa$loadings %>% view()
meta_efa$Structure
```


```{r}
# Fatores

meta_efa2 <- df_geral %>% select(58:74) %>% fa(nfactors = '4', cor='poly', 
            fm='wls', rotate = 'geominQ')

meta_efa2$e.values
meta_efa2$loadings %>% view()
```

```{r}
df_geral %>% select(58:61, 64) %>% psych::omega(digits=3,poly=TRUE) #0.93
df_geral %>% select(62,63,65:70) %>% omega(digits=3,poly=TRUE) #0.86
df_geral %>% select(71:74) %>% omega(digits=3,poly=TRUE) #0.83
```

# Análise de precisão
- Metas
```{r}
df_geral %>% select(58:61, 64) %>% psych::omega(digits=3,poly=TRUE) #0.93
df_geral %>% select(62,63,65:70) %>% omega(digits=3,poly=TRUE) #0.86
df_geral %>% select(71:74) %>% omega(digits=3,poly=TRUE) #0.83
df_geral %>% select(58:74) %>% omega(digits=3,poly=TRUE) #0.83
```

- HSE
```{r}
# Neuroticismo
# Ome - 0.92/ alfa - 0.88
df_geral %>% select(145,92,96,97,105,146) %>% omega(digits=3,poly=TRUE)
# Consci
# Ome 0.90/ alfa - 0.84
df_geral %>% select(90,91,95,101,147,148) %>% omega(digits=3,poly=TRUE)
# Extro
# 0.96 / 0.91
df_geral %>% select(149,150,116,117,151,119) %>% omega(digits=3,poly=TRUE)
# Amabilidade
# 0.90 / 0.83
df_geral %>% select(93,99,102,107,108,111) %>% omega(digits=3,poly=TRUE)
# Abertura
# 0.89 / 0.84
df_geral %>% select(94,100,103,110,112,114) %>% omega(digits=3,poly=TRUE)
```

-CE
```{r}
# Al 0.84 e Om 0.89
df_geral %>% select(12,16,19,26,34,37,40,42) %>% psych::omega(digits=3,poly=TRUE)
# 0.84 / 0.88
df_geral %>% select(15,22,25,137,32,35,38) %>% omega(digits=3,poly=TRUE)
# 0.72 / 0.76
df_geral %>% select(17,19,138,43) %>% omega(digits=3,poly=TRUE)
# 0.73 / 0.82
df_geral %>% select(13,18,21,23,30,33,44) %>% omega(digits=3,poly=TRUE)
# 0.65 / 0.73
df_geral %>% select(136,20,24,28,31,36,45) %>% omega(digits=3,poly=TRUE)

df_geral %>% select(12,16,19,26,34,37,40,42, 
                    15,22,25,137,32,35,38, 
                    17,19,138,43, 
                    13,18,21,23,30,33,44,
                    136,20,24,28,31,36,45) %>% omega(digits=3,poly=TRUE)
```

- Raciocínio verbal
```{r}
df_geral %>% select(123:134) %>% omega(digits=3,poly=TRUE)
```


# Análises descritivas  

```{r}
df_geral$Idade <- substr(df_geral$Idade,1,2)
```

```{r}
df_geral$Idade <- as.numeric(df_geral$Idade)
glimpse(df_geral)
```

```{r}
df_geral %>% select(Idade, Sala) %>% filter(Sala <= 6) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))

df_geral %>% select(Gênero, Sala) %>% filter(Sala <= 6) %>% group_by(Gênero) %>% count() %>% mutate(porc = n/(164+50+3+1)*100)
```

```{r}
df_geral(Idade, Sala) %>% filter(Sala == 7 | Sala == 8) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))

df_geral %>% select(Gênero, Sala) %>% filter(Sala == 7 | Sala == 8) %>% group_by(Gênero) %>% count() %>% mutate(porc = n/(35+9+1)*100)
```

```{r}
df_geral %>% slice(1:35) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(36:71) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(72:108) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(109:150) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(151:204) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(205:223) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(224:249) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
df_geral %>% slice(250:263) %>% summarise(mean(Idade), sd(Idade), min(Idade), max(Idade))
```


```{r}
summary(df_geral$Idade)
```

names(df_geral)

```{r}
df_geral %>% summarise(mean(rvtotal), sd(rvtotal), min(rvtotal), max(rvtotal))
df_geral %>% summarise(mean(HF1), sd(HF1), min(HF1), max(HF1))
df_geral %>% summarise(mean(HF2), sd(HF2), min(HF2), max(HF2))
df_geral %>% summarise(mean(HF3), sd(HF3), min(HF3), max(HF3))
df_geral %>% summarise(mean(HF4), sd(HF4), min(HF4), max(HF4))
df_geral %>% summarise(mean(HF5), sd(HF5), min(HF5), max(HF5))
```

```{r}
df_geral %>% summarise(mean(CF1), sd(CF1), min(CF1), max(CF1))
df_geral %>% summarise(mean(CF2), sd(CF2), min(CF2), max(CF2))
df_geral %>% summarise(mean(CF3), sd(CF3), min(CF3), max(CF3))
df_geral %>% summarise(mean(CF4), sd(CF4), min(CF4), max(CF4))
df_geral %>% summarise(mean(CF5), sd(CF5), min(CF5), max(CF5))
df_geral %>% summarise(mean(C_GERAL), sd(C_GERAL), min(C_GERAL), max(C_GERAL))
```

```{r}
df_geral %>% summarise(mean(MF1), sd(MF1), min(MF1), max(MF1))
df_geral %>% summarise(mean(MF2), sd(MF2), min(MF2), max(MF2))
df_geral %>% summarise(mean(MF3), sd(MF3), min(MF3), max(MF3))
df_geral %>% summarise(mean(MF_GERAL), sd(MF_GERAL), min(MF_GERAL), max(MF_GERAL))
```

```{r}
df_geral %>% summarise(mean(rvtotal), sd(rvtotal), min(rvtotal), max(rvtotal))
```
